### ISSUE TITLE
Issue with Play File code bundles on "CircuitPython Made Easy" - MP3s instead of WAV files

### ISSUE THREAD

**Issue by mjvo** [adafruit/Adafruit_CircuitPython_CircuitPlayground#123]
The "[first](https://learn.adafruit.com/pages/12271/elements/2989685/download?type=zip) and [second](https://learn.adafruit.com/pages/12271/elements/2989687/download?type=zip) "Download Project Bundles" linked to the code snippets on the [Play File page](https://learn.adafruit.com/circuitpython-made-easy-on-circuit-playground-express/play-file) of the _CircuitPython Made Easy on Circuit Playground Express and Bluefruit_ tutorial contains .mp3 instead of .wav files.

The code.py file, on the other hand, references .wav files.  

Can the .wav files be included in the project bundles as well, since the .mp3 files won't play even when referenced properly in the code?

**Comment by FoamyGuy** [comment]
I've spoken with the Learn dev team about this and the bundling system is now updated to include the .wav files in those project bundle downloads.
