### ISSUE TITLE
cpx.pixels.brightness on Circuit Playground Express Doesn't seem to really dim the leds

### ISSUE THREAD

**Issue by ondrovic** [adafruit/Adafruit_CircuitPython_CircuitPlayground#126]
I have tried setting the following between all the different ranges for `0.1` to `1.0` and the brightness level never seems to change

using the following code

```python
cpx.pixels.brightness = 0.1
```

Is there anyway to make the leds not so blinding?

**Comment by dhalbert** [comment]
Could you show your code? When I set the brightness, the current levels are decreased. What version of the library and CircuitPython are you using?
