### ISSUE TITLE
shake threshhold not available?

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_CircuitPlayground#21]
shake() does exist on my build but there's no shake_threshhold argument in the function?

![image](https://user-images.githubusercontent.com/1214161/33906117-ebb0a344-df4e-11e7-86f5-50b31e6c79e5.png)

**Comment by kattni** [comment]
I tested it when I was working with it initially. It doesn't work now?

**Comment by kattni** [comment]
Now works as it should. Thanks for catching this! 

Resolved by: https://github.com/adafruit/Adafruit_CircuitPython_CircuitPlayground/pull/22
