### ISSUE TITLE
replace express.py line 67 with

### ISSUE THREAD

**Issue by hexthat** [adafruit/Adafruit_CircuitPython_CircuitPlayground#37]
self._lux = (self._photocell.value * 3.3 / 100) - 15
        if self._lux > 1910:
            return print('OVERLOAD')
        elif self._lux < 30:
            return    print('UNDERLOAD')
        else:
            return print(self._lux)

**Comment by tannewt** [comment]
Why?

**Comment by hexthat** [comment]
tested this "value * 330 // (2 ** 16)" on my CPX with calibrated source and it was no where near
 
also
replacing line 67 with this made Lux equal to calibrated source at 56 lux

"return (self._photocell.value * 3.3 / 100) - 23"

**Comment by caternuson** [comment]
The code comments may be a little misleading. These names changed a bit early on, but currently we have both a `light` and a `lux` property defined here:
http://circuitpython.readthedocs.io/en/3.x/docs/design_guide.html#sensor-properties-and-units
So the `cpx.light` property isn't really a true SI lux value. (code comment should be changed)

Can you provide more details about your testing? If we adopt this, we should just add your improved math to a new property called `lux`.

**Comment by kattni** [comment]
@hexthat Do you have any more details on your testing? We need more information before we can consider adding your suggestion into the library. Thanks!

**Comment by caternuson** [comment]
Closing. Can reopen if conversation starts up again.
