### ISSUE TITLE
cpx variable manual

### ISSUE THREAD

**Issue by alin256** [adafruit/Adafruit_CircuitPython_CircuitPlayground#39]
Hello,
I have spent a few hours trying to find either documentation or code for cpx.
The manual says "Simply import the cpx variable from the module and then use it."
However I cannot find the specification of all functions/variables etc available in cpx, i.e. cpx.*
Can you point me to the documentation?

**Comment by jerryneedell** [comment]
There is aguide here:
https://learn.adafruit.com/circuitpython-made-easy-on-circuit-playground-express/circuit-playground-express-library
And additional information here:
http://circuitpython.readthedocs.io/projects/circuitplayground/en/latest/api.html
I hope that helps.

**Comment by kattni** [comment]
@alin256 Those are the two best places for documentation. 

The first is a Learn guide with extensive explanation and examples for each feature in the library. The second is Read the Docs which has each feature listed, but is meant for a lower level API look at the library. 

Both have all the features listed, so choose based on where you're starting. If you're new to this, start with the Learn guide. If you've been at this for ages, Read the Docs may be more of interest to you.

We're also around on the [Adafruit Discord](https://adafru.it/discord) in the #circuitpython channel. If you have further questions, that's another option for answers. We'd love to hear about any projects you're working on, so feel free to join us there anytime!

Good luck!
