### ISSUE TITLE
Asynchronous play_file

### ISSUE THREAD

**Issue by nruffilo** [adafruit/Adafruit_CircuitPython_CircuitPlayground#45]
When playing a sound, the code is fully blocked.  MakeCode and C let me play a sound as sync or async.  It would be great to have a parameter for sync/async if that's possible.

The big issue is that this library blocks the use of the audio port, so if I'm using this great library for other functionality, I have to use audio in sync mode or I can't use audio.

**Comment by kattni** [comment]
This library is designed to make getting started with and using the Circuit Playground Express and CircuitPython super simple. It is not designed to work with every possible project someone might come up with. It is meant more for getting started or writing up something quick and easy. We never intended to account for all potential use cases. 

If you reach a point where the library is a limiting factor in your code, it's probably time to stop using the Adafruit CircuitPython CircuitPlayground and start using the individual CircuitPython libraries you need.

If you are interested in submitting a PR with code for this, we are willing to consider it. However, bear in mind that this library is already massive and there are some very significant size limitations. This is why the library is a frozen module in the Circuit Playground Express build of CircuitPython. This is all information to consider if you decide you'd like to move forward with submitting a change to this library. Testing will involve building CircuitPython with a frozen module. This is something we can help you with if you're interested.

**Comment by nruffilo** [comment]
@kattni thank you for your response, and that makes perfect sense.  I don't mind re-factoring my code so that it makes use of the libraries directly - I just figured it might be something that would make sense for the CPX library.  I'm new to circuitpython and microcontroller programming so I'm still trying to figure out what's the "right" way to do things.  I come from the web-dev world, so very different considerations.  

If, in refactoring, I find that I can do so compactly, I'll add the code to this issue for consideration.

Thank you for your work on this.

**Comment by tannewt** [comment]
We won't change the library for this but feel free to follow up with example code. Thanks!
