### ISSUE TITLE
Sine wave may be rather quiet - add option to change to square wave

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/Adafruit_CircuitPython_CircuitPlayground#49]
This [forum post](https://forums.adafruit.com/viewtopic.php?f=58&t=149440) has made me wonder if MakeCode uses a square wave to drive the CPX speaker. I think these are considerably louder. Might be worth adding that as an option? Or replacement?

The new return to mid point approach for audio means that [0, 65535] isn't great as a minimalist square wave sample. Perhaps something along the lines of [32768, 65535, 65535, 65535, 65535, 65535, 0, 0, 0, 0, 0, 32768] might do the trick?

_SEE DISCUSSION in comments about power and heat before selecting square wave as better option!_

**Comment by kevinjwalters** [comment]
Worth understanding this discussion too: https://forums.adafruit.com/viewtopic.php?f=58&t=150363

I'll add some more to that forum post when I get time to test different waveforms around the problematic 2300 Hz frequency.

**Comment by deshipu** [comment]
By the way, I noticed that the sine wave has wildly varying loudness depending on the frequency — you can tell by playing the RTTTL library examples, some of the notes are *much* louder than others.

**Comment by ladyada** [comment]
it'll be loudest around 2-4KHz which is where its expecting to be driven, did i mention its a really simple  buzzer? :)

**Comment by deshipu** [comment]
Oh, sorry, I tested that on the Hallowing, with a "real" speaker connected.

**Comment by ladyada** [comment]
speaker will also have some resonance - adding a normalization filter would be possible for tones, but not for anything more complex

**Comment by kevinjwalters** [comment]
@deshipu How are you driving the "real" speaker? It's worth checking pk-pk levels and ensuring the waveform is what you expect.

For example, the full voltage output range from the CPX **A0** converted to AC is beyond the expected range for _some_ equipment, discussed on https://forums.adafruit.com/viewtopic.php?f=58&t=148520. I have a small amplifying speaker which shuts down after a few seconds when faced with full peak to peak up its 3.5mm input. For other equipment it's within spec.

**Comment by deshipu** [comment]
@kevinjwalters the Hallowing has a volume control, and I set it so that the speaker is far from its maximum.

**Comment by dhalbert** [comment]
Has anyone looked at the waveforms with a scope or Saleae analog to see the levels?

**Comment by deshipu** [comment]
I reported it at https://github.com/adafruit/Adafruit_CircuitPython_RTTTL/issues/12 and I will check the waveforms now and post there.

**Comment by kevinjwalters** [comment]
On theme of speaker peculiarities there's mention of the speaker getting "very hot" with length playing of notes. It happens to be MakeCode. Started a discussion on: https://forums.adafruit.com/viewtopic.php?f=58&t=150682

**Comment by hexthat** [comment]
PR #57 has volume control
use like
```python
from adafruit_circuitplayground.express import cpx

loud = (2**4)
quite = -(2**4)

cpx.play_tone(220, 1, loud)
```

**Comment by kevinjwalters** [comment]
Would be useful to document the volume variable including the apppropriate range of values and the default?

**Comment by kevinjwalters** [comment]
Just tried MakeCode (15-May-2019) and output as viewed on **A0** is a triangle wave with a tiny touch of jaggedness.

**Comment by kevinjwalters** [comment]
More MakeCode shenanigans:
- https://github.com/microsoft/pxt-arcade/issues/975
- https://github.com/microsoft/pxt-common-packages/pull/528

**Comment by kevinjwalters** [comment]
Not relevant for CPX specific code but there's an interesting practical limit of around 53000 on PyPortal DACs: https://forums.adafruit.com/viewtopic.php?f=24&t=153703

**Comment by ryanskeith** [comment]
The square ton is definitely louder.  We could implement volume control as well.  But perhaps this is another isuse.
