### ISSUE TITLE
Rename express singleton

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_CircuitPlayground#6]
What do you think about renaming the singleton
`circuit = Express()`
to be either `express` or `cpx` (or some other similar name)?

I think it should be short and/or meaningful. `cpx` is short. `express` implies it's an instance of class `Express`, which it is. `circuit` I'm not so sure about, since, well, it's not a circuit. Maybe `circuitp`? That's a little harder to read out loud.

**Comment by ladyada** [comment]
CPX is good if it is a library just for the CPX

**Comment by kattni** [comment]
It is for the Circuit Playground Express-specific library. I agree CPX gives a much clearer scope to the available features in the library. I think it's an excellent idea.

**Comment by tannewt** [comment]
I'd prefer `cpx` over `express` because `express` can easily be confused with `Express`.

**Comment by kattni** [comment]
Excellent! I'll update it to `cpx`, update the code examples, and get it to you for review.

**Comment by kattni** [comment]
Update to `cpx` complete.
