### ISSUE TITLE
Add ability to set the sensitivity of the accelerometer.

### ISSUE THREAD

**Issue by mertzjames** [adafruit/Adafruit_CircuitPython_CircuitPlayground#60]
It would be nice if we could set the sensitivity of the accelerometer to the 4 choices:

* 2g
* 4g
* 8g
* 16g

This can be down hackishly by:

```python
import adafruit_lis3dh
from adafruit_circuitplayground.express import cpx

cpx._lis3dh.range = adafruit_lis3dh.RANGE_16_G
```

but I think that it would be good to create a direct interface to the change.

**Comment by mertzjames** [comment]
This is something that I would even be willing to work on if that's possible.  I haven't contributed to the repo before but would like to.

**Comment by tannewt** [comment]
Hi James, I think the hackish way is fine. We want to keep the CPX lib as small and simple as we can. For advanced uses like this we expect folks to dig into the underlying libraries like you have.
