### ISSUE TITLE
Tap detection on Circuit Playground Bluefruit hypersensitive

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_CircuitPlayground#77]
Tap detection seems to be more sensitive on Bluefruit than Express. May be worth looking into.

**Comment by dhalbert** [comment]
The accelerometer is in the center of the board on CPX, but is to the right of the slide switch on CPB. That could make a difference.

**Comment by Panometric** [comment]
It defaults to all axes, but you can limit to just Z, which should negate the location difference. 

In Circuit Python: 
`cpx._lis3dh.set_tap(tap=1, threshold=120, time_limit=4, click_cfg=0x10)

https://cdn-shop.adafruit.com/datasheets/LIS3DHappnote.pdf
https://github.com/adafruit/Adafruit_CircuitPython_LIS3DH/blob/master/adafruit_lis3dh.py

Therefore clock_cfg=0x10 Sets to only Z axis, single click.

**Comment by dherrada** [comment]
@kattni Is this resolved?

**Comment by kattni** [comment]
@dherrada I have not looked into it beyond creating the issue.

**Comment by dherrada** [comment]
Definitely more sensitive on the bluefruit. I know you can set the threshold so my plan is to just raise the tap threshold for the bluefruit so that it behaves like the express does.
