### ISSUE TITLE
Tilting arpeggios example fails on higher frequency notes on CPB

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_CircuitPlayground#78]
The example runs initially until it is tilted in a manner that results in a higher frequency tone.

```
Traceback (most recent call last):
  File "code.py", line 132, in <module>
  File "code.py", line 96, in run
  File "code.py", line 129, in change_tone_if_needed
  File "adafruit_circuitplayground/circuit_playground_base.py", line 922, in start_tone
ValueError: Sample rate too high. It must be less than 62500
```

**Comment by jepler** [comment]
I'm assuming the demo is
https://github.com/dcbriccetti/Adafruit_CircuitPython_CircuitPlayground/blob/tilt-instrument/examples/advanced_examples/circuitplayground_tilting_arpeggios.py
linked from https://blog.adafruit.com/2019/09/30/tilting-arpeggios-for-circuitpython-and-circuit-playground-express-circuitplaygroundexpress-circuitpython-electronicmusic-circuitpython/

**Comment by kattni** [comment]
@jepler Yes but the demo is also available in this repo under advanced examples.

**Comment by jepler** [comment]
@kattni thanks, I found it after wrestling with git for a little bit :)
