### ISSUE TITLE
Allow play_file() to return immediately instead of block?

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_CircuitPlayground#88]
A user in the #help-with-circuitpython discord channel noticed that when you play a wave file using cpx.play_file() it's blocking so that no other code will execute until after the wave file is complete. However if you use `AudioOut.play()` it's non-blocking and therefore allows the code to continue on running while the wave file plays.

They are going to be leading a workshop with some students and for the sake of simplicity want to be able to stick to using mainly the circuitplayground library to do everything rather than worrying about all of the separate libraries and imports individually.  But they would like the ability to play the wave file and still continue executing code during it's playback rather than waiting for it to complete.

At first glance I noticed the [while loop here](https://github.com/adafruit/Adafruit_CircuitPython_CircuitPlayground/blob/62f8df1e2c00a6a5dd5dcf433b9c0cc0270c6bfb/adafruit_circuitplayground/circuit_playground_base.py#L740) appears to be responsible for the blocking behavior of `play_file()` and I thought maybe we could add an optional parameter that could be used to decide whether to use the blocking while loop or not. 

After thinking it over some more and taking another look at the code I think it's a bit more complicated than that since `play_file()` is setting the `_speaker_enable` pin back to False after the the blocking loop. Also I think the way that `with` is used to setup the audio object would get rid of that object if the function returned immediately. 

I've created an issue here for now to see if there is any interest/opposition for having a way within this library to play wave files in a non-blocking manner. As well as see if anyone has thoughts or ideas on how it could be implemented given the `_speaker_enable` pin, and `with` issues mentioned above. 

I do think it would be nice to allow it, but I can also see a case being made that the circuitplayground library really is aimed at total beginners and adding anything that allows for asynchronous functionality could lead to confusion if everything they have experienced up to that point has been synchronous. If this functionality is added I do think the default behavior should remain blocking, and in order to make it non-blocking it should require something explicit that hopefully someone is unlikely to do by accident.

**Comment by kattni** [comment]
@FoamyGuy Is this something you're interested in adding?

**Comment by FoamyGuy** [comment]
Yes. I'll make a PR for it this week. I can't think of a way to set the `_speaker_enable` pin back to False after the audio is done playing. I will make a note in the documentation of the new flag that it will remain True after the call if it's not blocking.

**Comment by FoamyGuy** [comment]
I tried to make this change but hit a snag. The way this code is accessing the AudioOut using a `with` context block makes it need to be blocking as far as I could tell. I tried returning from `play_file()` immediately but it did not play my wav file, I believe it's due to the context getting closed when it returns. 

I will close this for now since it seems like it would require a bit more substantial refactoring to keep ahold of AudioOut instead of accessing it in a new context each time. And you can already use AudioOut directly to play a file in a non-blocking manner.
