### ISSUE TITLE
Cannot play custom wav file

### ISSUE THREAD

**Issue by ShreyaKhurana** [adafruit/Adafruit_CircuitPython_CircuitPlayground#97]
Hi, I was trying to run a simple snippet using the `cpx.play_file` function:

```
from adafruit_circuitplayground.express import cpx

while True:
    if cpx.button_a:
        cpx.play_file("final.wav")
    if cpx.button_b:
        cpx.play_file("low_fade.wav")
```
I see the following error message because of `final.wav` which is my own file, in Mu:

```
Traceback (most recent call last):
  File "code.py", line 6, in <module>
  File "adafruit_circuitplayground/circuit_playground_base.py", line 741, in play_file
  File "adafruit_circuitplayground/circuit_playground_base.py", line 738, in play_file
ValueError: Data chunk must follow fmt chunk
```

But the image properties are as follows, the sample rate is < 22kHz and it's 16 bit file. i can play it fine in iTunes. Can someone please help with this?
<img width="443" alt="Screen Shot 2020-08-01 at 5 44 35 PM" src="https://user-images.githubusercontent.com/8307030/89112921-2c44c300-d41f-11ea-8d4a-2c65cf407236.png">

**Comment by tannewt** [comment]
Hi! How did you make the wavefile? I think we usually [use Audacity](https://learn.adafruit.com/microcontroller-compatible-audio-file-conversion).

We don't support all of the different versions of Wave because we are limited on code space.

**Comment by ShreyaKhurana** [comment]
I was using an online converter to get to the required sample rate and sample size. I'll try Audacity then!

**Comment by dherrada** [comment]
Hey @ShreyaKhurana were you able to get this working?

**Comment by ShreyaKhurana** [comment]
Yup, got it working, just had to convert the file through Audacity, even iTunes didn't work for me though.

**Comment by petewarden** [comment]
As a note for anyone who wants a command line solution, I was able to successfully convert MP3s to CP-acceptable wavs using this ffmpeg command:
```
ffmpeg -i some.mp3 -f wav -flags +bitexact -acodec pcm_s16le -ac 1 -ar 22050 some.wav
```

This was using ffmpeg 3.4.11. The important part seems to be the `-flags +bitexact`, since that removes the additional chunk that the CircuitPlayground library can't handle. Some older versions of ffmpeg use `-bitexact` instead, apparently.

**Comment by demc** [comment]
> As a note for anyone who wants a command line solution, I was able to successfully convert MP3s to CP-acceptable wavs using this ffmpeg command:
> 
> ```
> ffmpeg -i some.mp3 -f wav -flags +bitexact -acodec pcm_s16le -ac 1 -ar 22050 some.wav
> ```
> 
> This was using ffmpeg 3.4.11. The important part seems to be the `-flags +bitexact`, since that removes the additional chunk that the CircuitPlayground library can't handle. Some older versions of ffmpeg use `-bitexact` instead, apparently.

If anyone is having issues with ffmpeg 4 or 5, please use the following (notice the subtle change to the `bitexact` flag):

```bash
ffmpeg -i input_file.ogg -f wav -bitexact -acodec pcm_s16le -ac 1 -ar 22050 output_file.wav
```

As far as I could tell, `-bitexact` removes the ISFT metadata that was preventing the file from playing.

**Comment by mperino** [comment]
@demc 's ffmpeg solution worked on: ffmpeg 4.4.2-0ubuntu0.22.04.1
Much appreicated, and should be added to the docs..

**Comment by s-light** [comment]
just stumbled upon this -
think also that is a important note for the docks!!!
